// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEucUXmfGKlWHD6mkFDkxpYO7YoN5lx6k',
    appId: '1:412610443622:web:9923875d4c0654ecb570a7',
    messagingSenderId: '412610443622',
    projectId: 'lingobreeze-9d447',
    authDomain: 'lingobreeze-9d447.firebaseapp.com',
    storageBucket: 'lingobreeze-9d447.firebasestorage.app',
    measurementId: 'G-4Q5LKHVTZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1WVl3MJ6S-igftNrG9P7DG0I71yY_DgQ',
    appId: '1:412610443622:android:25cc12856807d689b570a7',
    messagingSenderId: '412610443622',
    projectId: 'lingobreeze-9d447',
    storageBucket: 'lingobreeze-9d447.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD68-B5ezP6Z3CPQ8fctm4l9u5AWJB9t4c',
    appId: '1:412610443622:ios:3447753cb0607fa9b570a7',
    messagingSenderId: '412610443622',
    projectId: 'lingobreeze-9d447',
    storageBucket: 'lingobreeze-9d447.firebasestorage.app',
    iosBundleId: 'com.example.lingobreeze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD68-B5ezP6Z3CPQ8fctm4l9u5AWJB9t4c',
    appId: '1:412610443622:ios:3447753cb0607fa9b570a7',
    messagingSenderId: '412610443622',
    projectId: 'lingobreeze-9d447',
    storageBucket: 'lingobreeze-9d447.firebasestorage.app',
    iosBundleId: 'com.example.lingobreeze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEucUXmfGKlWHD6mkFDkxpYO7YoN5lx6k',
    appId: '1:412610443622:web:76413c0fae67d00cb570a7',
    messagingSenderId: '412610443622',
    projectId: 'lingobreeze-9d447',
    authDomain: 'lingobreeze-9d447.firebaseapp.com',
    storageBucket: 'lingobreeze-9d447.firebasestorage.app',
    measurementId: 'G-JTNQCD8KD9',
  );
}
